"""Source-of-truth mock data for seeding the SQLite database.

Keys use camelCase to match the API response shape (and the frontend's
TypeScript `Load` interface) so the data round-trips without renaming.
"""

COMMON_TASKS = [
    {"label": "Booked - Verify with Carrier", "status": "To Do"},
    {"label": "Verify Carrier Compliance", "status": "To Do"},
    {"label": "Verify Load before Pickup", "status": "To Do"},
    {"label": "Verify Pick Appointments Scheduled", "status": "To Do"},
    {"label": "Verify Delivery Appointments Scheduled", "status": "To Do"},
    {"label": "Driver Onboarding", "status": "To Do"},
    {"label": "In Transit Monitoring", "status": "In Progress"},
    {"label": "Proof of Delivery", "status": "To Do"},
]

LOADS = [
    {
        "id": "236568",
        "loadNo": "236568",
        "customerLoadNo": "153241",
        "customer": "Brazos Valley Produce Co.",
        "status": "At Pickup",
        "pickup": {"city": "Houston", "state": "TX", "dateTime": "Sat Jun 13 · 03:30 PM CDT"},
        "dropoff": {"city": "Dothan", "state": "AL", "dateTime": "Mon Jun 15 · 06:00 AM"},
        "carrier": "Blue Mesa Freight LLC",
        "driver": {"name": "Marcus Ellison", "phone": "+1 (850) 624-9108", "rating": 0},
        "customerRate": 3400,
        "carrierRate": 2700,
        "distanceMiles": 695,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 42000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 33,
        "currentLocation": "Mesquite, TX",
        "tasks": [
            {"label": "Booked - Verify with Carrier", "status": "To Do"},
            {"label": "Verify Carrier Compliance", "status": "Done"},
            {"label": "Verify Load before Pickup", "status": "Done"},
            {"label": "Verify Pick Appointments Scheduled", "status": "Done"},
            {"label": "Verify Delivery Appointments Scheduled", "status": "Done"},
            {"label": "Driver Onboarding", "status": "Done"},
            {"label": "In Transit Monitoring", "status": "In Progress"},
            {"label": "Proof of Delivery", "status": "To Do"},
        ],
        "postings": [
            {
                "partner": "Trucker Path",
                "referenceNo": "261771",
                "status": "Unposted",
                "comments": "Solo | Pick 1 : Houston, TX | Drop 1 : Dothan, AL",
                "price": 2700,
                "postId": "TP065000000152EDEAA0...",
                "postedBy": "Maya Raman",
                "postedAt": "Jun 13, 2026, 10:12 AM",
                "contactMethods": "Primary Phone, Email",
                "unpostAfter": "2 hours 0 mins",
                "unpostedBy": "System",
                "unpostedAt": "Jun 13, 2026, 10:15 AM",
                "agent": {
                    "name": "Mara Voice Agent",
                    "phone": "+1 (408) 712-3360",
                    "email": "mara@laneloop.com",
                },
            },
            {
                "partner": "DAT",
                "referenceNo": "021474",
                "status": "Unposted",
                "comments": "Solo | Pick 1 : Houston, TX | Drop 1 : Dothan, AL",
            },
        ],
    },
    {
        "id": "236564",
        "loadNo": "236564",
        "customerLoadNo": "demo load",
        "customer": "Mercado Vista Distribution",
        "status": "Cancelled",
        "pickup": {"city": "Pharr", "state": "TX", "dateTime": "Sat Jun 13 · 03:00 PM CDT"},
        "dropoff": {"city": "Eagle Pass", "state": "TX", "dateTime": "Sun Jun 14 · 08:00 AM"},
        "customerRate": 1000,
        "distanceMiles": 150,
        "equipment": "Dry Van",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 30000,
        "cargoValue": "$10,000 - $25,000",
        "tasks": COMMON_TASKS,
    },
    {
        "id": "236556",
        "loadNo": "236556",
        "customerLoadNo": "4400057459 & 4400057215",
        "customer": "Rio Loma Berry Co.",
        "status": "Enroute",
        "pickup": {"city": "Pharr", "state": "TX", "dateTime": "Sat Jun 13 · 10:00 AM CDT"},
        "dropoff": {"city": "Salinas", "state": "CA", "dateTime": "Mon Jun 15 · 02:00 PM"},
        "carrier": "Summit Ridge Transport Inc",
        "driver": {"name": "Aman Grewal", "phone": "+1 (559) 555-0142", "rating": 4},
        "customerRate": 6700,
        "carrierRate": 5500,
        "distanceMiles": 1980,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Team",
        "weightLbs": 41500,
        "cargoValue": "$100,000 - $150,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "currentLocation": "Las Cruces, NM",
        "tasks": COMMON_TASKS,
        "postings": [
            {
                "partner": "Trucker Path",
                "referenceNo": "261902",
                "status": "Posted",
                "comments": "Team | Pick 1 : Pharr, TX | Drop 1 : Salinas, CA",
                "price": 5500,
                "postId": "TP065000000153FACB1...",
                "postedBy": "Mara Voice Agent",
                "postedAt": "Jun 13, 2026, 09:40 AM",
                "contactMethods": "Primary Phone, Email",
                "unpostAfter": "4 hours 0 mins",
                "agent": {
                    "name": "Mara Voice Agent",
                    "phone": "+1 (408) 712-3360",
                    "email": "mara@laneloop.com",
                },
            },
        ],
    },
    {
        "id": "236548",
        "loadNo": "236548",
        "customerLoadNo": "4400057322",
        "customer": "Rio Loma Berry Co.",
        "status": "Created",
        "pickup": {"city": "Pharr", "state": "TX", "dateTime": "Mon Jun 15 · 11:30 AM"},
        "dropoff": {"city": "Salinas", "state": "CA", "dateTime": "Wed Jun 17 · 08:00 AM"},
        "customerRate": 6300,
        "distanceMiles": 1980,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Team",
        "weightLbs": 41000,
        "cargoValue": "$100,000 - $150,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS[:3],
        "postings": [
            {
                "partner": "DAT",
                "referenceNo": "021588",
                "status": "Posted",
                "comments": "Team | Pick 1 : Pharr, TX | Drop 1 : Salinas, CA",
                "price": 5900,
                "postId": "DAT065000000161AB22...",
                "postedBy": "Mara Voice Agent",
                "postedAt": "Jun 14, 2026, 08:05 AM",
                "contactMethods": "Primary Phone, Email",
                "unpostAfter": "6 hours 0 mins",
                "agent": {
                    "name": "Mara Voice Agent",
                    "phone": "+1 (408) 712-3360",
                    "email": "mara@laneloop.com",
                },
            },
        ],
    },
    {
        "id": "236544",
        "loadNo": "236544",
        "customer": "Coastal Ridge Farms",
        "status": "Published",
        "pickup": {"city": "Guadalupe", "state": "CA", "dateTime": "Mon Jun 15 · 04:00 PM"},
        "dropoff": {"city": "Nampa", "state": "ID", "dateTime": "Wed Jun 17 · 08:00 AM"},
        "customerRate": 5000,
        "distanceMiles": 920,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 38000,
        "cargoValue": "$50,000 - $75,000",
        "temperatureMode": "Continuous",
        "temperatureF": 36,
        "tasks": COMMON_TASKS[:3],
        "postings": [
            {
                "partner": "Truckstop",
                "referenceNo": "338201",
                "status": "Posted",
                "comments": "Solo | Pick 1 : Guadalupe, CA | Drop 1 : Nampa, ID",
                "price": 4200,
                "postId": "TS065000000148CCD90...",
                "postedBy": "Maya Raman",
                "postedAt": "Jun 14, 2026, 07:20 AM",
                "contactMethods": "Primary Phone, Email",
                "unpostAfter": "8 hours 0 mins",
                "agent": {
                    "name": "Mara Voice Agent",
                    "phone": "+1 (408) 712-3360",
                    "email": "mara@laneloop.com",
                },
            },
        ],
    },
    {
        "id": "236048",
        "loadNo": "236048",
        "customerLoadNo": "7633787",
        "customer": "Pacific Leaf Growers",
        "status": "Booked",
        "pickup": {"city": "Ventura", "state": "CA", "dateTime": "Mon Jun 15 · 08:00 AM"},
        "dropoff": {"city": "Sunnyside", "state": "WA", "dateTime": "Wed Jun 17 · 02:45 AM"},
        "carrier": "Cascade Valley Carriers LLC",
        "driver": {"name": "Harjit Sandhu", "phone": "+1 (509) 555-0188", "rating": 5},
        "customerRate": 5760,
        "carrierRate": 5500,
        "distanceMiles": 1100,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 40000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS,
    },
    {
        "id": "236052",
        "loadNo": "236052",
        "customerLoadNo": "7697595",
        "customer": "Pacific Leaf Growers",
        "status": "Created",
        "pickup": {"city": "Ventura", "state": "CA", "dateTime": "Fri Jun 19 · 08:00 AM PDT"},
        "dropoff": {"city": "Tacoma", "state": "WA", "dateTime": "Sun Jun 21 · 10:00 AM"},
        "customerRate": 6075,
        "distanceMiles": 1200,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 40000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS[:3],
        "postings": [
            {
                "partner": "Trucker Path",
                "referenceNo": "262044",
                "status": "Posted",
                "comments": "Solo | Pick 1 : Ventura, CA | Drop 1 : Tacoma, WA",
                "price": 5200,
                "postId": "TP065000000159BBEF7...",
                "postedBy": "Mara Voice Agent",
                "postedAt": "Jun 14, 2026, 06:48 AM",
                "contactMethods": "Primary Phone, Email",
                "unpostAfter": "12 hours 0 mins",
                "agent": {
                    "name": "Mara Voice Agent",
                    "phone": "+1 (408) 712-3360",
                    "email": "mara@laneloop.com",
                },
            },
        ],
    },
    {
        "id": "236040",
        "loadNo": "236040",
        "customerLoadNo": "7633801",
        "customer": "Pacific Leaf Growers",
        "status": "Booked",
        "pickup": {"city": "Ventura", "state": "CA", "dateTime": "Mon Jun 15 · 08:00 AM"},
        "dropoff": {"city": "Sunnyside", "state": "WA", "dateTime": "Wed Jun 17 · 02:45 AM"},
        "carrier": "North Fork Refrigerated Inc",
        "driver": {"name": "Gurpreet Mann", "phone": "+1 (509) 555-0177", "rating": 4},
        "customerRate": 5760,
        "carrierRate": 5500,
        "distanceMiles": 1100,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 40000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS,
    },
]
