"""Source-of-truth mock data for seeding the SQLite database.

Keys use camelCase to match the API response shape (and the frontend's
TypeScript `Load` interface) so the data round-trips without renaming.
"""

COMMON_TASKS = [
    {"label": "Booked by AI Agent - Verify with Carrier", "status": "To Do"},
    {"label": "Verify Carrier Compliance", "status": "To Do"},
    {"label": "Verify Load before Pickup", "status": "To Do"},
    {"label": "Verify Pick Appointments Scheduled", "status": "To Do"},
    {"label": "Verify Delivery Appointments Scheduled", "status": "To Do"},
    {"label": "Driver Onboarding - AI Agent", "status": "To Do"},
    {"label": "In Transit Monitoring - AI Agent", "status": "In Progress"},
    {"label": "Proof of Delivery", "status": "To Do"},
]

LOADS = [
    {
        "id": "236568",
        "loadNo": "236568",
        "customerLoadNo": "153241",
        "customer": "Lipman Family Farms (Texas)",
        "status": "At Pickup",
        "pickup": {"city": "Dallas", "state": "TX", "dateTime": "Sat Jun 13 · 03:30 PM CDT"},
        "dropoff": {"city": "New Brockton", "state": "AL", "dateTime": "Mon Jun 15 · 06:00 AM"},
        "carrier": "BH Trans Inc",
        "driver": {"name": "Steven Holmes", "phone": "+1 (850) 718-7337", "rating": 0},
        "customerRate": 3400,
        "carrierRate": 2700,
        "distanceMiles": 695,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 42000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 33,
        "currentLocation": "Garland, TX",
        "tasks": [
            {"label": "Booked by AI Agent - Verify with Carrier", "status": "To Do"},
            {"label": "Verify Carrier Compliance", "status": "Done"},
            {"label": "Verify Load before Pickup", "status": "Done"},
            {"label": "Verify Pick Appointments Scheduled", "status": "Done"},
            {"label": "Verify Delivery Appointments Scheduled", "status": "Done"},
            {"label": "Driver Onboarding - AI Agent", "status": "Done"},
            {"label": "In Transit Monitoring - AI Agent", "status": "In Progress"},
            {"label": "Proof of Delivery", "status": "To Do"},
        ],
        "postings": [
            {
                "partner": "Trucker Path",
                "referenceNo": "261771",
                "status": "Unposted",
                "comments": "Solo | Pick 1 : Dallas, TX | Drop 1 : New Brockton, AL",
                "price": 2700,
                "postId": "TP065000000152EDEAA0...",
                "postedBy": "Umair Ahmed",
                "postedAt": "Jun 13, 2026, 10:12 AM",
                "contactMethods": "Primary Phone, Email",
                "unpostAfter": "2 hours 0 mins",
                "unpostedBy": "System",
                "unpostedAt": "Jun 13, 2026, 10:15 AM",
                "agent": {
                    "name": "Sarah Voice Agent",
                    "phone": "+1 (408) 843-5941",
                    "email": "stella@hwyhaul.com",
                },
            },
            {
                "partner": "DAT",
                "referenceNo": "021474",
                "status": "Unposted",
                "comments": "Solo | Pick 1 : Dallas, TX | Drop 1 : New Brockton, AL",
            },
        ],
    },
    {
        "id": "236564",
        "loadNo": "236564",
        "customerLoadNo": "test load",
        "customer": "Abarrotera Central",
        "status": "Cancelled",
        "pickup": {"city": "Mcallen", "state": "TX", "dateTime": "Sat Jun 13 · 03:00 PM CDT"},
        "dropoff": {"city": "Laredo", "state": "TX", "dateTime": "Sun Jun 14 · 08:00 AM"},
        "customerRate": 1000,
        "distanceMiles": 150,
        "equipment": "Dry Van",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 30000,
        "cargoValue": "$10,000 - $25,000",
        "tasks": COMMON_TASKS,
    },
    {
        "id": "236556",
        "loadNo": "236556",
        "customerLoadNo": "4400057459 & 4400057215",
        "customer": "Hortifrut Imports",
        "status": "Enroute",
        "pickup": {"city": "Mcallen", "state": "TX", "dateTime": "Sat Jun 13 · 10:00 AM CDT"},
        "dropoff": {"city": "Watsonville", "state": "CA", "dateTime": "Mon Jun 15 · 02:00 PM"},
        "carrier": "Khokhar Road Carrier Inc",
        "driver": {"name": "Harbhajan Singh", "phone": "+1 (559) 555-0142", "rating": 4},
        "customerRate": 6700,
        "carrierRate": 5500,
        "distanceMiles": 1980,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Team",
        "weightLbs": 41500,
        "cargoValue": "$100,000 - $150,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "currentLocation": "El Paso, TX",
        "tasks": COMMON_TASKS,
        "postings": [
            {
                "partner": "Trucker Path",
                "referenceNo": "261902",
                "status": "Posted",
                "comments": "Team | Pick 1 : Mcallen, TX | Drop 1 : Watsonville, CA",
                "price": 5500,
                "postId": "TP065000000153FACB1...",
                "postedBy": "Sarah Voice Agent",
                "postedAt": "Jun 13, 2026, 09:40 AM",
                "contactMethods": "Primary Phone, Email",
                "unpostAfter": "4 hours 0 mins",
                "agent": {
                    "name": "Sarah Voice Agent",
                    "phone": "+1 (408) 843-5941",
                    "email": "stella@hwyhaul.com",
                },
            },
        ],
    },
    {
        "id": "236548",
        "loadNo": "236548",
        "customerLoadNo": "4400057322",
        "customer": "Hortifrut Imports",
        "status": "Created",
        "pickup": {"city": "Mcallen", "state": "TX", "dateTime": "Mon Jun 15 · 11:30 AM"},
        "dropoff": {"city": "Watsonville", "state": "CA", "dateTime": "Wed Jun 17 · 08:00 AM"},
        "customerRate": 6300,
        "distanceMiles": 1980,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Team",
        "weightLbs": 41000,
        "cargoValue": "$100,000 - $150,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS[:3],
    },
    {
        "id": "236544",
        "loadNo": "236544",
        "customer": "Windset Farms",
        "status": "Published",
        "pickup": {"city": "Santa Maria", "state": "CA", "dateTime": "Mon Jun 15 · 04:00 PM"},
        "dropoff": {"city": "Boise", "state": "ID", "dateTime": "Wed Jun 17 · 08:00 AM"},
        "customerRate": 5000,
        "distanceMiles": 920,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 38000,
        "cargoValue": "$50,000 - $75,000",
        "temperatureMode": "Continuous",
        "temperatureF": 36,
        "tasks": COMMON_TASKS[:3],
    },
    {
        "id": "236048",
        "loadNo": "236048",
        "customerLoadNo": "7633787",
        "customer": "Chiquita Fresh North America LLC",
        "status": "Booked",
        "pickup": {"city": "Oxnard", "state": "CA", "dateTime": "Mon Jun 15 · 08:00 AM"},
        "dropoff": {"city": "Grandview", "state": "WA", "dateTime": "Wed Jun 17 · 02:45 AM"},
        "carrier": "Raptor Trans LLC",
        "driver": {"name": "Manjit Gill", "phone": "+1 (509) 555-0188", "rating": 5},
        "customerRate": 5760,
        "carrierRate": 5500,
        "distanceMiles": 1100,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 40000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS,
    },
    {
        "id": "236052",
        "loadNo": "236052",
        "customerLoadNo": "7697595",
        "customer": "Chiquita Fresh North America LLC",
        "status": "Created",
        "pickup": {"city": "Oxnard", "state": "CA", "dateTime": "Fri Jun 19 · 08:00 AM PDT"},
        "dropoff": {"city": "Seattle", "state": "WA", "dateTime": "Sun Jun 21 · 10:00 AM"},
        "customerRate": 6075,
        "distanceMiles": 1200,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 40000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS[:3],
    },
    {
        "id": "236040",
        "loadNo": "236040",
        "customerLoadNo": "7633801",
        "customer": "Chiquita Fresh North America LLC",
        "status": "Booked",
        "pickup": {"city": "Oxnard", "state": "CA", "dateTime": "Mon Jun 15 · 08:00 AM"},
        "dropoff": {"city": "Grandview", "state": "WA", "dateTime": "Wed Jun 17 · 02:45 AM"},
        "carrier": "S Sandhar Transport Inc",
        "driver": {"name": "Gurpreet Sandhar", "phone": "+1 (509) 555-0177", "rating": 4},
        "customerRate": 5760,
        "carrierRate": 5500,
        "distanceMiles": 1100,
        "equipment": "Reefer",
        "loadSize": "Full Truck Load (FTL)",
        "driverType": "Solo Driver",
        "weightLbs": 40000,
        "cargoValue": "$75,000 - $100,000",
        "temperatureMode": "Continuous",
        "temperatureF": 34,
        "tasks": COMMON_TASKS,
    },
]
